# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9599692ce07fdeaa8beeb1f9b2b5a41135550d9f7d039f501be811a8abe9234ed318e93cba87163ddb54c31f81184a87f019608630b73e8545133278129726

test:
  secret_key_base: 45fc6c5f1c3402a728ec96e73f631e41e49a46767de9519cc87c1539a07faf6a2a907e651ddf71be98e046d44ea92de7649408da991775968ab56a5c582647ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
